# Generated by Django 3.2.4 on 2023-11-05 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictCancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('20-29', '20-29'), ('30-39', '30-39'), ('40-49', '40-49'), ('50-59', '50-59'), ('60-69', '60-69'), ('70-79', '70-79')], max_length=50)),
                ('menopause', models.CharField(choices=[('ge40', 'ge40'), ('lt40', 'lt40'), ('premeno', 'premeno')], max_length=50)),
                ('tumor_size', models.CharField(choices=[('0-4', '0-4'), ('5-9', '5-9'), ('10-14', '10-14'), ('15-19', '15-19'), ('20-24', '20-24'), ('25-29', '25-29'), ('30-34', '30-34'), ('35-39', '35-39'), ('40-44', '40-44'), ('45-49', '45-49'), ('50-54', '50-54')], max_length=50)),
                ('inv_nodes', models.CharField(choices=[('0-2', '0-2'), ('3-5', '3-5'), ('6-8', '6-8'), ('9-11', '9-11'), ('12-14', '12-14'), ('15-17', '15-17'), ('24-26', '24-26')], max_length=50)),
                ('node_caps', models.CharField(choices=[('no', 'no'), ('yes', 'yes')], max_length=50)),
                ('irradiate', models.CharField(choices=[('no', 'no'), ('yes', 'yes')], max_length=50)),
                ('classification', models.CharField(max_length=50)),
            ],
        ),
    ]
